---
- hosts : webservers
  become : true
  become_user : root
  tasks :          
   - name : Install Docker
     yum:
       name: docker
       state : present    

   - name : Docker start
     service :
       name : docker
       state : started
       
   - name : Pull the container
     command : docker pull shraddharane/myimage:$BUILD_NUMBER
     
   - name : Run the container
     command : docker run -itd --name container1 -P myimage:$BUILD_NUMBER
      
      

   
     
