---
- hosts : webservers
  become : true
  become_user : root
  tasks :    
       
   - name : Install Docker
     yum:
       name: docker
       state : present    

   - name : Docker start
     service :
       name : docker
       state : started

   - name : Pull docker image
     command : docker pull devopsedu/webapp

   - name : Run Docker Image
     command : docker run -itd --name devops -P  devopsedu/webapp
     
   - name : Run apache server inside the container
     command : docker exec devops bash -c "service apache2 start"
