---
- hosts : webservers
  become : true
  become_user : root
  tasks :
   - name: Install httpd
     yum:
      name: httpd
      state: present
     when: ansible_os_family == "RedHat"
    
   - name: Start httpd
     service:
      name: httpd 
      state: started 
      enabled: yes
     when: ansible_os_family == "RedHat"
   - name : Install Docker
     yum:
       name: docker
       state : present

   - name : Docker start
     service :
       name : docker
       state : started

   - name : Pull docker image
     command : docker pull devopsedu/webapp

   - name : Run Docker Image
     command : docker run -itd -p 8089:80 devopsedu/webapp
