---
- hosts : webservers
  become : true
  become_user : root
  tasks :    
   - name : Create directory
     file :
       path : /tmp/gitrepo
       state : directory
       
   - name : Install Docker
     yum:
       name: docker
       state : present    

   - name : Docker start
     service :
       name : docker
       state : started

   
     
