---
- hosts : webservers
  become : true
  become_user : root
  tasks :    
   - name : Install git
     yum :
      name : git
      state : present
      
   - name : Git clone
     git :
      repo : https://github.com/shraddharane1395/CertiProject.git
      dest : /tmp/repo      
       
   - name : Install Docker
     yum:
       name: docker
       state : present    

   - name : Docker start
     service :
       name : docker
       state : started

   - name : Build docker file
     command : chdir /tmp/gitrepo docker build -t myimage:v1 .

   - name : Run Docker image
     command : docker run -itd --name certimage -P myimage:v1
     
